# Generated by Django 5.1.7 on 2025-04-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
