# Generated by Django 5.1.7 on 2025-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_descripcion_programa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
