# Generated by Django 5.1.7 on 2025-04-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_alter_programa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='descripcion',
        ),
    ]
