# Generated by Django 5.1.7 on 2025-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0005_remove_programa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='programas/'),
        ),
    ]
