# Generated by Django 5.1.7 on 2025-05-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0006_alter_programa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='imagen',
        ),
    ]
