# Generated by Django 5.1.7 on 2025-03-11 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_options_usuarios_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ultimo_reinicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ultimo reinicio de puntos'),
        ),
    ]
