# Generated by Django 5.1.7 on 2025-03-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la actividad')),
                ('puntos', models.FloatField(verbose_name='Puntos (+/-)')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
