# Generated by Django 5.1.7 on 2025-04-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('programas', '0003_alter_programa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='programas.programa'),
        ),
    ]
